#!/bin/sh

function get_ipv4() {
    iface=${1:-$(uci -q get ddns.main.v4_iface)}
    ip addr show dev ${iface} | grep 'inet ' | awk '{print $2}' | sort | head -n 1
}

function get_ipv6() {
    iface=${1:-$(uci -q get ddns.main.v6_iface)}
    ip addr show dev ${iface} | grep 'inet6 ' | grep dynamic | grep -v deprecated | awk '{print $2}' | sed 's|/.*||g' | sort | head -n 1
}

function put_ip() {
    curl -m 10 -X PUT "https://api.cloudflare.com/client/v4/zones/${3}/dns_records/${4}" \
        -H "X-Auth-Email: ${1}" \
        -H "Authorization: Bearer ${2}" \
        -H "Content-Type:application/json" \
        --data "{\"type\":\"${5}\",\"name\":\"${6}\",\"content\":\"${7}\",\"ttl\":${8},\"proxied\":${9}}"
}

function log() {
    log='/tmp/log/ddns'
    echo "[$(date +%Y%m%d.%H%M%S)] PUT ${2} TO ${3}" > ${log}.${1}
}

function main() {
    email=$(uci -q get ddns.auth.email)
    token=$(uci -q get ddns.auth.token)
    records=$(uci -q get ddns.set.records)
    ipv4=''
    ipv6=''
    while [ -n "${records}" ]; do
        for record in ${records}; do
            zone=$(uci -q get ddns.${record}.zone)
            type=$(uci -q get ddns.${record}.type)
            name=$(uci -q get ddns.${record}.name)
            ttl=$(uci -q get ddns.${record}.ttl)
            proxied=$(uci -q get ddns.${record}.proxied)
            iface=$(uci -q get ddns.${record}.iface)
            if [ "${type}" == "A" ]; then
                ip=$(get_ipv4 ${iface})
                if [ "${ipv4}" != "${ip}" ]; then
                    log '4' ${ip} ${name}
                    put_ip ${email} ${token} ${zone} ${record} ${type} ${name} ${ip} ${ttl} ${proxied}
                    if [ $? -eq 0 ]; then
                        ipv4=${ip}
                    fi
                fi
            fi
            if [ "${type}" == "AAAA" ]; then
                ip=$(get_ipv6 ${iface})
                if [ "${ipv6}" != "${ip}" ]; then
                    log '6' ${ip} ${name}
                    put_ip ${email} ${token} ${zone} ${record} ${type} ${name} ${ip} ${ttl} ${proxied}
                    if [ $? -eq 0 ]; then
                        ipv6=${ip}
                    fi
                fi
            fi
        done
        sleep 120
    done
}

main
