#!/bin/sh

function get_ipv4() {
    iface=${1:-$(uci -q get ddns.main.v4_iface)}
    ip addr show dev ${iface} | grep 'inet ' | awk '{print $2}' | sort | head -n 1
}

function get_ipv6() {
    iface=${1:-$(uci -q get ddns.main.v6_iface)}
    ip addr show dev ${iface} | grep 'inet6 ' | grep dynamic | grep -v deprecated | awk '{print $2}' | sed 's|/.*||g' | sort | head -n 1
}

function put_ip() {
    curl -m 10 -X PUT "https://api.cloudflare.com/client/v4/zones/${3}/dns_records/${4}" \
        -H "X-Auth-Email: ${1}" \
        -H "Authorization: Bearer ${2}" \
        -H "Content-Type:application/json" \
        --data "{\"type\":\"${5}\",\"name\":\"${6}\",\"content\":\"${7}\",\"ttl\":${8},\"proxied\":${9}}"
}

function set_addr() {
    mkdir -p /tmp/run/ddns
    echo "${2}" > /tmp/run/ddns/${1}
}

function get_addr() {
    file=/tmp/run/ddns/${1}
    if [ -f "${file}" ]; then
        cat "${file}"
    fi
}

function log() {
    logger -t ddns "${1}: PUT ${2} TO ${3}"
}

function main() {
    email=$(uci -q get ddns.auth.email)
    token=$(uci -q get ddns.auth.token)
    records=$(uci -q get ddns.set.records)
    while [ -n "${records}" ]; do
        for record in ${records}; do
            addr=$(get_addr ${record})
            zone=$(uci -q get ddns.${record}.zone)
            type=$(uci -q get ddns.${record}.type)
            name=$(uci -q get ddns.${record}.name)
            ttl=$(uci -q get ddns.${record}.ttl)
            proxied=$(uci -q get ddns.${record}.proxied)
            iface=$(uci -q get ddns.${record}.iface)
            if [ "${type}" == "A" ]; then
                ip=$(get_ipv4 ${iface})
                if [ "${addr}" != "${ip}" ]; then
                    log ${record} ${ip} ${name}
                    put_ip ${email} ${token} ${zone} ${record} ${type} ${name} ${ip} ${ttl} ${proxied}
                    if [ $? -eq 0 ]; then
                        set_addr ${record} ${ip}
                    fi
                fi
            elif [ "${type}" == "AAAA" ]; then
                ip=$(get_ipv6 ${iface})
                if [ "${addr}" != "${ip}" ]; then
                    log ${record} ${ip} ${name}
                    put_ip ${email} ${token} ${zone} ${record} ${type} ${name} ${ip} ${ttl} ${proxied}
                    if [ $? -eq 0 ]; then
                        set_addr ${record} ${ip}
                    fi
                fi
            fi
        done
        sleep 120
    done
}

main
