#!/bin/sh /etc/rc.common
#
# Copyright (C) 2022 hev <r@hev.cc>
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#

. /lib/functions.sh

START=90
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param respawn
	procd_set_param command /usr/bin/ddns
	procd_close_instance
}
